name: release

on: 
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Package
        uses: BigWigsMods/packager@master
